[package]
name = "auto_impl"
version = "0.1.0"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]

[lib]
proc-macro = true

[dependencies]
quote = "*"
auto_impl_internals = { version = "*", path = "../auto_impl_internals" }