language: rust
rust:
  - nightly
  - beta
  - stable

script:
  - cargo build --verbose || travis_terminate 1
  - cargo test --verbose || travis_terminate 1

matrix:
  include:
    - name: "Build & test on nightly WITH nightly feature"
      rust: nightly
      script:
        - cargo build --verbose --features=nightly || travis_terminate 1
        - cargo test --verbose --features=nightly || travis_terminate 1

env:
  global:
    - RUSTFLAGS="--deny warnings"
