[package]
name = "auto_impl"
version = "0.2.0"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]
license = "MIT"
description = "Automatically implement traits for common smart pointers and closures"
repository = "https://github.com/KodrAus/auto_impl"
documentation = "https://docs.rs/auto_impl/"
keywords = ["plugin"]
categories = ["development-tools"]
readme = "README.md"

[badges]
travis-ci = { repository = "KodrAus/auto_impl" }

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4.6"
quote = "0.6.3"
# TODO: remove "extra-traits", it's just for debugging
syn = { version = "0.14.4", features = ["full", "extra-traits"] }
