cargo-features = ["edition"]

[package]
name = "auto_impl"
version = "0.2.0"
authors = [
    "Ashley Mannix <ashleymannix@live.com.au>",
    "Lukas Kalbertodt <lukas.kalbertodt@gmail.com>",
]
license = "MIT"
description = "Automatically implement traits for common smart pointers and closures"
repository = "https://github.com/KodrAus/auto_impl"
documentation = "https://docs.rs/auto_impl/"
keywords = ["plugin"]
categories = ["development-tools"]
readme = "README.md"
autotests = true
edition = '2018'

[badges]
travis-ci = { repository = "KodrAus/auto_impl" }


[lib]
proc-macro = true

[features]
nightly = ["proc-macro2/nightly"]

[dependencies]
proc-macro2 = { version = "0.4.6" }
quote = "0.6.3"
syn = { version = "0.14.4", features = ["full", "visit-mut"] }

[dev-dependencies]
build-plan = "0.1.1"
libtest-mimic = "0.1.0"

[[test]]
name = "compile-fail"
path = "tests/compile-fail.rs"
harness = false

[[test]]
name = "compile-pass"
path = "tests/compile-pass.rs"
harness = false
